# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Game(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, board: str=None, status: str=None):
        """
        Game - a model defined in Swagger

        :param board: The board of this Game.
        :type board: str
        :param status: The status of this Game.
        :type status: str
        """
        self.swagger_types = {
            'board': str,
            'status': str
        }

        self.attribute_map = {
            'board': 'board',
            'status': 'status'
        }

        self._board = board
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Game':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The game of this Game.
        :rtype: Game
        """
        return deserialize_model(dikt, cls)

    @property
    def board(self) -> str:
        """
        Gets the board of this Game.
        The board state

        :return: The board of this Game.
        :rtype: str
        """
        return self._board

    @board.setter
    def board(self, board: str):
        """
        Sets the board of this Game.
        The board state

        :param board: The board of this Game.
        :type board: str
        """
        if board is None:
            raise ValueError("Invalid value for `board`, must not be `None`")

        self._board = board

    @property
    def status(self) -> str:
        """
        Gets the status of this Game.
        The game status, read-only, the client can not POST or PUT this

        :return: The status of this Game.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """
        Sets the status of this Game.
        The game status, read-only, the client can not POST or PUT this

        :param status: The status of this Game.
        :type status: str
        """
        allowed_values = ["RUNNING", "X_WON", "O_WON", "DRAW"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

